# Generated by Django 5.2 on 2025-04-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=255)),
                ('segment', models.CharField(choices=[('Pharma', 'Pharma SFA'), ('FMCG', 'FMCG'), ('Payroll', 'Payroll')], max_length=255)),
                ('dealType', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=255)),
                ('dealWonDate', models.DateField()),
                ('setupCharges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthlySubscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('newMarketPenetration', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('newMarketCountry', models.CharField(blank=True, max_length=255, null=True)),
                ('dealownerSalesPerson', models.CharField(max_length=255)),
                ('followUpSalesPerson', models.CharField(max_length=255)),
                ('demo1SalesPerson', models.CharField(max_length=255)),
                ('demo2SalesPerson', models.CharField(max_length=255)),
            ],
        ),
    ]
