# Generated by Django 5.2 on 2025-04-21 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0002_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='dealownerSalesPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_deals', to='incentives.userprofile'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='demo1SalesPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo1_deals', to='incentives.userprofile'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='demo2SalesPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo2_deals', to='incentives.userprofile'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='followUpSalesPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_deals', to='incentives.userprofile'),
        ),
    ]
