# Generated by Django 5.2 on 2025-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentivesetup',
            name='enable_topper_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incentivesetup',
            name='enable_topper_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incentivesetup',
            name='subscription_below_50_per',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
