# Generated by Django 5.2 on 2025-05-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0003_incentivesetup_enable_topper_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentivesetup',
            name='enable_leader_1',
            field=models.BooleanField(default=False),
        ),
    ]
