# Generated by Django 5.2 on 2025-04-21 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0003_alter_deal_dealownersalesperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='followUpSalesPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incentives.userprofile'),
        ),
    ]
