# Generated by Django 5.2 on 2025-04-21 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0004_alter_deal_followupsalesperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=10)),
                ('annual_target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentives.userprofile')),
            ],
        ),
    ]
