# Generated by Django 5.2 on 2025-05-03 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0004_incentivesetup_enable_leader_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='leadSource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadsource', to='incentives.userprofile'),
        ),
        migrations.AlterField(
            model_name='highvaluedealslab',
            name='deal_type_high',
            field=models.CharField(default='domestic', max_length=20),
        ),
        migrations.AlterField(
            model_name='setupchargeslab',
            name='deal_type_setup',
            field=models.CharField(default='domestic', max_length=20),
        ),
        migrations.AlterField(
            model_name='toppermonthslab',
            name='deal_type_top',
            field=models.CharField(default='domestic', max_length=20),
        ),
    ]
