# Generated by Django 5.2 on 2025-04-22 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0005_annualtarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20)),
                ('financial_year', models.CharField(max_length=20)),
                ('new_market_value', models.PositiveIntegerField(default=0)),
                ('dom_lead_share', models.FloatField(default=0)),
                ('dom_followup_share', models.FloatField(default=0)),
                ('dom_online_demo_share', models.FloatField(default=0)),
                ('dom_direct_meeting_share', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_75_90_achievement', models.BooleanField(default=True)),
                ('enable_90_95_achievement', models.BooleanField(default=True)),
                ('enable_95_100_achievement', models.BooleanField(default=True)),
                ('enable_above100_achievement', models.BooleanField(default=True)),
                ('enable_8month_achievement', models.BooleanField(default=True)),
                ('enable_6month_achievement', models.BooleanField(default=True)),
                ('enable_4month_achievement', models.BooleanField(default=True)),
                ('enable_0month_achievement', models.BooleanField(default=True)),
                ('enable_topper_1', models.BooleanField(default=True)),
                ('enable_topper_2', models.BooleanField(default=True)),
                ('enable_leader_1', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighValueDealSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.PositiveIntegerField()),
                ('max_value', models.PositiveIntegerField()),
                ('incentive_percent', models.FloatField()),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_value_slabs', to='incentives.monthlyincentive')),
            ],
        ),
        migrations.CreateModel(
            name='SetupChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.PositiveIntegerField()),
                ('max_amount', models.PositiveIntegerField()),
                ('incentive_percent', models.FloatField()),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_slabs', to='incentives.monthlyincentive')),
            ],
        ),
        migrations.CreateModel(
            name='TopperMonthRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=50)),
                ('min_subscription', models.PositiveIntegerField()),
                ('incentive_percent', models.FloatField()),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topper_slabs', to='incentives.monthlyincentive')),
            ],
        ),
    ]
