# Generated by Django 5.2 on 2025-05-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0006_transaction_payouttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.CharField(default='Non Approve', max_length=255),
        ),
    ]
