# Generated by Django 5.2 on 2025-04-25 11:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('incentives', '0006_monthlyincentive_yearlyincentive_highvaluedealslab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTargetIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.CharField(max_length=50)),
                ('enable_75_90_achievement', models.BooleanField(default=True)),
                ('enable_90_95_achievement', models.BooleanField(default=True)),
                ('enable_95_100_achievement', models.BooleanField(default=True)),
                ('enable_above100_achievement', models.BooleanField(default=True)),
                ('enable_8month_achievement', models.BooleanField(default=True)),
                ('enable_6month_achievement', models.BooleanField(default=True)),
                ('enable_4month_achievement', models.BooleanField(default=True)),
                ('enable_0month_achievement', models.BooleanField(default=True)),
                ('enable_topper_1', models.BooleanField(default=True)),
                ('enable_topper_2', models.BooleanField(default=True)),
                ('enable_leader_1', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('change_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('change_summary', models.TextField(blank=True)),
                ('full_data_snapshot', models.JSONField()),
            ],
            options={
                'ordering': ['-change_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_view', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentives.module')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_selectable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.DeleteModel(
            name='YearlyIncentive',
        ),
        migrations.RemoveField(
            model_name='highvaluedealslab',
            name='incentive',
        ),
        migrations.RemoveField(
            model_name='highvaluedealslab',
            name='incentive_percent',
        ),
        migrations.RemoveField(
            model_name='highvaluedealslab',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='highvaluedealslab',
            name='min_value',
        ),
        migrations.AlterUniqueTogether(
            name='monthlyincentive',
            unique_together={('deal_type', 'financial_year')},
        ),
        migrations.RemoveField(
            model_name='setupchargerule',
            name='incentive',
        ),
        migrations.RemoveField(
            model_name='setupchargerule',
            name='incentive_percent',
        ),
        migrations.RemoveField(
            model_name='toppermonthrule',
            name='incentive',
        ),
        migrations.RemoveField(
            model_name='toppermonthrule',
            name='incentive_percent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='annualtarget',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='annualtarget',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annualtarget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='annualtarget',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deal',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='highvaluedealslab',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='highvaluedealslab',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='highvaluedealslab',
            name='incentive_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='highvaluedealslab',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='highvaluedealslab',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='highvaluedealslab',
            name='rule_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='high_value_slabs', to='incentives.monthlyincentive'),
        ),
        migrations.AddField(
            model_name='highvaluedealslab',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='highvaluedealslab',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='deal_owner',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='demo_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='demo_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='follow_up',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='lead_source',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='new_market_incentive_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monthlyincentive',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setupchargerule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='setupchargerule',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setupchargerule',
            name='incentive_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='setupchargerule',
            name='rule_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_charge_rules', to='incentives.monthlyincentive'),
        ),
        migrations.AddField(
            model_name='setupchargerule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='setupchargerule',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='toppermonthrule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='toppermonthrule',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='toppermonthrule',
            name='incentive_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='toppermonthrule',
            name='rule_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topper_month_rules', to='incentives.monthlyincentive'),
        ),
        migrations.AddField(
            model_name='toppermonthrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='toppermonthrule',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyincentive',
            name='deal_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlyincentive',
            name='financial_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='setupchargerule',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='setupchargerule',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='toppermonthrule',
            name='min_subscription',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='toppermonthrule',
            name='segment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='highvaluedealslab',
            table='single_value_rules',
        ),
        migrations.AlterModelTable(
            name='monthlyincentive',
            table='rule_sets',
        ),
        migrations.AlterModelTable(
            name='setupchargerule',
            table='setup_charge_rules',
        ),
        migrations.AlterModelTable(
            name='toppermonthrule',
            table='topper_month_rules',
        ),
        migrations.AddField(
            model_name='changelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incentives.userprofile'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='deal',
            name='leadSource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incentives.leadsource'),
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentives.role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incentives.role'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incentives.segment'),
        ),
        migrations.RemoveField(
            model_name='monthlyincentive',
            name='dom_direct_meeting_share',
        ),
        migrations.RemoveField(
            model_name='monthlyincentive',
            name='dom_followup_share',
        ),
        migrations.RemoveField(
            model_name='monthlyincentive',
            name='dom_lead_share',
        ),
        migrations.RemoveField(
            model_name='monthlyincentive',
            name='dom_online_demo_share',
        ),
        migrations.RemoveField(
            model_name='monthlyincentive',
            name='new_market_value',
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('role', 'module')},
        ),
    ]
