# Generated by Django 5.2 on 2025-05-05 08:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0007_deal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouttransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payouttransaction',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payouttransaction',
            name='incentive_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='incentives.transaction'),
        ),
        migrations.AlterField(
            model_name='payouttransaction',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payouttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payouttransaction',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='incentive_component_type',
            field=models.CharField(choices=[('setup', 'Setup'), ('new_market', 'New Market'), ('topper_month', 'Topper of the Month'), ('single_high', 'Single High Value')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
