# Generated by Django 5.2 on 2025-04-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0007_annualtargetincentive_changelog_leadsource_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='net_salary',
        ),
        migrations.AddField(
            model_name='annualtarget',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
