# Generated by Django 5.2 on 2025-05-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0008_alter_payouttransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouttransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_trans', to='incentives.userprofile'),
        ),
    ]
