# Generated by Django 5.2 on 2025-04-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0008_remove_userprofile_net_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='module_name',
            new_name='module',
        ),
    ]
