# Generated by Django 5.2 on 2025-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0009_rename_module_name_module_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='changed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changelog',
            name='model_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
