# Generated by Django 5.2 on 2025-05-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0009_alter_payouttransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='incentives.userprofile'),
        ),
    ]
