# Generated by Django 5.2 on 2025-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0010_userprofile_team_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coordinator',
            field=models.BooleanField(default=True),
        ),
    ]
