# Generated by Django 5.2 on 2025-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0010_changelog_changed_data_changelog_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='full_data_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
