# Generated by Django 5.2 on 2025-05-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0011_userprofile_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='refDocs',
            field=models.FileField(blank=True, null=True, upload_to='deals/ref_docs/'),
        ),
        migrations.AddField(
            model_name='deal',
            name='subAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='subDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='subrenewDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='dealWonDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='setupCharges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
