# Generated by Django 5.2 on 2025-04-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0011_alter_changelog_full_data_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
