# Generated by Django 5.2 on 2025-04-25 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0012_alter_changelog_model_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={},
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='change_summary',
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='change_timestamp',
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='full_data_snapshot',
        ),
        migrations.AddField(
            model_name='changelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changelog',
            name='change_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='changed_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='model_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
