# Generated by Django 5.2 on 2025-05-29 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0013_alter_userprofile_team_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payouttransaction',
            name='deal_id',
        ),
        migrations.AddField(
            model_name='payouttransaction',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incentives.deal'),
        ),
        migrations.CreateModel(
            name='TragetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('transaction_type', models.CharField(choices=[('Earned', 'Earned'), ('To Recover', 'To Recover')], max_length=50)),
                ('incentive_component_type', models.CharField(choices=[('setup', 'Setup'), ('new_market', 'New Market'), ('topper_month', 'Topper of the Month'), ('single_high', 'Single High Value')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('freeze', models.BooleanField(default=False)),
                ('is_latest', models.BooleanField(default=True)),
                ('eligibility_status', models.CharField(choices=[('Pending', 'Pending'), ('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible')], default='Pending', max_length=50)),
                ('eligibility_message', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incentives.deal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incentives.userprofile')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
