# Generated by Django 5.2 on 2025-04-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0014_module_created_at_module_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='new_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
