# Generated by Django 5.2 on 2025-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0015_changelog_new_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='object_id',
            field=models.CharField(max_length=100),
        ),
    ]
