# Generated by Django 5.2 on 2025-05-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0015_rename_tragettransaction_targettransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targettransaction',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'TargetTransaction', 'verbose_name_plural': 'TargetTransaction'},
        ),
        migrations.AlterField(
            model_name='targettransaction',
            name='incentive_component_type',
            field=models.CharField(choices=[('subscription', 'Subscription')], max_length=100),
        ),
    ]
