# Generated by Django 5.2 on 2025-05-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0016_alter_targettransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='deal_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incentives.deal'),
        ),
    ]
