# Generated by Django 5.2 on 2025-04-26 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0017_changelog_created_by_changelog_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualtargetincentive',
            name='reduction_period',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='toppermonthrule',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_segment', to='incentives.segment'),
        ),
    ]
