# Generated by Django 5.2 on 2025-05-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0018_annualtargetincentive_reduction_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='dealType',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=15),
        ),
    ]
