# Generated by Django 5.2 on 2025-06-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0018_rename_deal_transaction_deal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('monthly', 'Monthly Incentive Job'), ('yearly', 'Yearly Incentive Job')], max_length=10)),
                ('schedule', models.CharField(max_length=255)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('button_class', models.CharField(default='btn-outline-primary', max_length=50)),
            ],
        ),
    ]
