# Generated by Django 5.2.2 on 2025-06-07 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0019_jobrunlog_scheduledjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouttransaction',
            name='incentive_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='incentives.transaction'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
