# Generated by Django 5.2.2 on 2025-06-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0020_alter_payouttransaction_incentive_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualtarget',
            name='status',
            field=models.CharField(default='Not Completed', max_length=255),
        ),
    ]
