# Generated by Django 5.2.2 on 2025-06-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0021_annualtarget_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incentivesetup',
            old_name='deal_owner',
            new_name='domestic_deal_owner',
        ),
        migrations.RenameField(
            model_name='incentivesetup',
            old_name='demo_1',
            new_name='domestic_demo_1',
        ),
        migrations.RenameField(
            model_name='incentivesetup',
            old_name='demo_2',
            new_name='domestic_demo_2',
        ),
        migrations.RenameField(
            model_name='incentivesetup',
            old_name='follow_up',
            new_name='domestic_follow_up',
        ),
        migrations.RenameField(
            model_name='incentivesetup',
            old_name='lead_source',
            new_name='domestic_lead_source',
        ),
        migrations.AddField(
            model_name='incentivesetup',
            name='international_deal_owner',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='incentivesetup',
            name='international_demo_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='incentivesetup',
            name='international_demo_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='incentivesetup',
            name='international_follow_up',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='incentivesetup',
            name='international_lead_source',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
