# Generated by Django 5.2.3 on 2025-06-10 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0022_rename_deal_owner_incentivesetup_domestic_deal_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incentives.userprofile'),
        ),
    ]
