# Generated by Django 5.2.3 on 2025-06-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0023_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='monthly_rule_executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='yearly_rule_executed',
            field=models.BooleanField(default=False),
        ),
    ]
